### ISSUE TITLE
Not working with VS 2019

### ISSUE THREAD

**Issue by voodoomotion** [vovan4ik123/assimp-Cpp-OpenGL-skeletal-animation#9]
Thanks for sharing this project, i think it could be really helpful!

Unfortunately i'm trying to build it in VS2019, there are quite a few warnings, it builds successfully, however when I run the exe it displays some white text in a small black window, then I think it's trying to maximise the window before crashing/closing.  Basically nothing happens apart from that, I can't see or control any model.  Appreciate any help, many thanks!

**Comment by vovan4ik123** [comment]
It not depends on VS version. I use last VS2019 version and it works. Update your drivers and SDK.
